name: Run all tests

on:
  push:
    branches: 
      main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run tests with Gradle Wrapper
      run: ./gradlew test
